######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 24 17:21:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    data.h \
    mytextedit.h
FORMS += mainwindow.ui \
    mytextedit.ui
SOURCES += main.cpp mainwindow.cpp \
    data.cpp \
    mytextedit.cpp
RESOURCES += mainwindow.qrc
